
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToStylesLayer.ahk
#Include *i Layer1\ToMacrosLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Style\Styl_Naglowek1.ahk
#Include *i Style\Styl_Naglowek2.ahk
#Include *i Style\Styl_Naglowek3.ahk
#Include *i Style\Styl_Naglowek4.ahk
#Include *i Style\Styl_Naglowek5.ahk
#Include *i Style\Styl_Naglowek6.ahk
#Include *i Style\Styl_Naglowek7.ahk
#Include *i Style\Styl_Naglowek8.ahk
#Include *i Style\Styl_NaglowekSpisuTresci.ahk
#Include *i Style\Styl_Normalny.ahk
#Include *i Style\Styl_NormalnyPomiedzy.ahk
#Include *i Style\Styl_Ukryty.ahk
#Include *i Style\Styl_Homoglify.ahk
#Include *i Style\Styl_Bezpieczenstwo.ahk
#Include *i Style\Styl_LiniaPrzerwy.ahk
#Include *i Style\Styl_Rysunek.ahk
#Include *i Style\Styl_PodpisPodRysunkiem.ahk
#Include *i Style\Styl_PolaTekstowe.ahk
#Include *i Style\Styl_Tabela.ahk
#Include *i Style\Styl_TabelaBezKrawedzi.ahk
#Include *i Style\Styl_NormalnyWTabeli.ahk
#Include *i Style\Styl_PodpisTabeli.ahk
#Include *i Style\Styl_Wypunktowanie.ahk
#Include *i Style\Styl_WypunktowanieReferencji.ahk
#Include *i Style\Styl_WypunktowanieWTabeli.ahk
#Include *i Style\Styl_NormalnyPunktowany.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Makra\SzablonPL.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Makra\SzablonEN.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek1.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek2.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek3.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek4.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek5.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek6.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek7.ahk
#Include *i Class_ImageButton.ahk
#Include *i WarstwaWord\Style\Styl_NaglowekSpisuTresci.ahk
#Include *i WarstwaWord\Style\Styl_Normalny.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyPomiedzy.ahk
#Include *i WarstwaWord\Style\Styl_Ukryty.ahk
#Include *i WarstwaWord\Style\Styl_Bezpieczenstwo.ahk
#Include *i WarstwaWord\Style\Styl_Homoglify.ahk
#Include *i WarstwaWord\Style\Styl_LiniaPrzerwy.ahk
#Include *i Class_ImageButton.ahk
#Include *i WarstwaWord\Style\Styl_PodpisPodRysunkiem.ahk
#Include *i WarstwaWord\Style\Styl_PolaTekstowe.ahk
#Include *i WarstwaWord\Style\Styl_Tabela.ahk
#Include *i WarstwaWord\Style\Styl_TabelaBezKrawedzi.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyWTabeli.ahk
#Include *i WarstwaWord\Style\Styl_PodpisTabeli.ahk
#Include *i WarstwaWord\Style\Styl_Wypunktowanie.ahk
#Include *i WarstwaWord\Style\Styl_WypunktowanieReferencji.ahk
#Include *i WarstwaWord\Style\Styl_WypunktowanieWTabeli.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyPunktowany.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek8.ahk
#Include *i WarstwaWord\Style\Styl_Rysunek.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek8.ahk
#Include *i WarstwaWord\Makra\SzablonPL.ahk
#Include *i WarstwaWord\Makra\SzablonEN.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\testtesttest.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToStylesLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToMacrosLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\Makra\SzablonPL.ahk
#Include *i WarstwaWord\Makra\SzablonEN.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_identyfikator.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_ListaZmian.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTresci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTabel.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisRysunkow.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisOznaczenGraficznych.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_tabela.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Kanwa.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaInformacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Zastrzezenie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_PierwszaStronaZwykla.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_NaglowekZwykly.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StopkaZwykla.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStronaObrazek.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStronaObrazek.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStrona.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\Makra\UstawMarginesy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i WarstwaWord\Makra\UstawMarginesy.ahk
#Include *i WarstwaWord\Makra\UsunWielokrotneSpacje.ahk
#Include *i WarstwaWord\Makra\PierwszaStrona.ahk
#Include *i WarstwaWord\Makra\UpdateSVNFields.ahk
#Include *i WarstwaWord\Makra\DodajNrSVN.ahk
#Include *i WarstwaWord\Makra\TwardaSpacja.ahk
#Include *i WarstwaWord\Makra\ZielenKolor.ahk
#Include *i WarstwaWord\Makra\UsunKolor.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToTCLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToTablesLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_DrugaStrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Producent.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_NewNextListPelna.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaInformacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaOstrzezenie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTresci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_InformacjeODokumencie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisSkrotow.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Referencje.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_ReferencjePodrozdzialy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SRAC.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OInstrukcji.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Ilustracje.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_newlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_newnumlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextnumlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_AXMCaly.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ReprezentacjaGraficznaAXM.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PodstawyKontroliNiezajetosci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ObslugaiEksploatacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PrzeznaczoneUzytkowanie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ZakresDostawy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Podziekowania.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_pustastrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_blankpage.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_KanwaZIkonami.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PrawaAutorskie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_RyzykoResztkowe.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_TekstOryginalny.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_UsuwanieOstatniejSekcji.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Utylizacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_UtylizacjaOpakowania.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToSVNLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisSkrotow.ahk
#Include *i WarstwaTotalCommander\SVN\SVNUpdate.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCommit.ahk
#Include *i WarstwaTotalCommander\SVN\SVNAdd.ahk
#Include *i WarstwaTotalCommander\SVN\SVNDelete.ahk
#Include *i WarstwaTotalCommander\SVN\SVNShowLog.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCheckLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNGetLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaWord\Tabele\InsertColumnToTheLeft.ahk
#Include *i WarstwaWord\Tabele\InsertColumnToTheRight.ahk
#Include *i WarstwaWord\Tabele\InsertTableRowAbove.ahk
#Include *i WarstwaWord\Tabele\InsertTableRowBelow.ahk
#Include *i WarstwaWord\Tabele\DeleteTableColumn.ahk
#Include *i WarstwaWord\Tabele\DeleteTableRow.ahk
#Include *i WarstwaWord\Tabele\SeparateTableCell1xRow2xColumn.ahk
#Include *i WarstwaWord\Tabele\SeparateTableCell2xRow1xColumn.ahk
#Include *i WarstwaWord\Tabele\MergeTableCells.ahk
#Include *i WarstwaWord\Tabele\MarkAllTableCells.ahk
#Include *i WarstwaWord\Tabele\AlignTableToPageBorder.ahk
#Include *i WarstwaWord\Tabele\DopasowanieTabeli.ahk
#Include *i WarstwaWord\Tabele\RepeatTableHeader.ahk
#Include *i WarstwaWord\Tabele\TableRowsAllowBreakAcrossPages.ahk
#Include *i WarstwaWord\Tabele\AlignTableCellConntentToLeft.ahk
#Include *i WarstwaWord\Tabele\AlignTableCellConntentToMiddle.ahk
#Include *i WarstwaWord\Tabele\TableCellColorVoestalpine.ahk
#Include *i WarstwaWord\MakraOgolne\ShowHiddenText.ahk
#Include *i WarstwaWord\MakraOgolne\StrikeThroughText.ahk
#Include *i WarstwaWord\MakraOgolne\Header.ahk
#Include *i WarstwaWord\MakraOgolne\Footer.ahk
#Include *i WarstwaWord\MakraOgolne\FullPath.ahk
#Include *i WarstwaWord\MakraOgolne\ZielenKolor.ahk
#Include *i WarstwaWord\MakraOgolne\UsunKolor.ahk
#Include *i WarstwaWord\MakraOgolne\GranicePol.ahk
#Include *i WarstwaWord\MakraOgolne\PrintToPdf.ahk
#Include *i WarstwaWord\MakraOgolne\ChangeZoom.ahk
#Include *i WarstwaWord\MakraOgolne\DisplayGridLines.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleRuler.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToParagraphLayer.ahk
#Include *i Layer1\ToSettingsLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToImagesLayer.ahk
#Include *i Layer1\ToReviewLayer.ahk
#Include *i Layer1\ToListsLayer.ahk
#Include *i WarstwaWord\Obrazki\HorizontalLine.ahk
#Include *i WarstwaWord\Obrazki\PolaTekstowe.ahk
#Include *i WarstwaWord\Akapity\Lista1Poz.ahk
#Include *i WarstwaWord\Akapity\Lista1PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista2Poz.ahk
#Include *i WarstwaWord\Akapity\Lista2PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista3Poz.ahk
#Include *i WarstwaWord\Akapity\Lista3PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista4Poz.ahk
#Include *i WarstwaWord\Akapity\Lista4PozKont.ahk
#Include *i WarstwaWord\Akapity\ChangeLanguage.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SzablonPL.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SzablonEN.ahk
#Include *i WarstwaWord\Recenzja\EditComment.ahk
#Include *i WarstwaWord\Recenzja\GoToNextComment.ahk
#Include *i WarstwaWord\Recenzja\GoToPreviousComment.ahk
#Include *i WarstwaWord\Recenzja\NextChangeOrComment.ahk
#Include *i WarstwaWord\Recenzja\PreviousChangeOrComment.ahk
#Include *i WarstwaWord\Recenzja\DeleteCurrentComment.ahk
#Include *i WarstwaWord\Recenzja\AcceptChange.ahk
#Include *i WarstwaWord\Recenzja\RejectChange.ahk
#Include *i WarstwaWord\Wypunktowania\BB_newlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_newnumlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nextnumlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_NewNextListPelna.ahk
#Include *i WarstwaWord\Wypunktowania\BB_NewNextListPelna.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToTCLayer.ahk
#Include *i WarstwaTotalCommander\SVN\SVNUpdate.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCommit.ahk
#Include *i WarstwaTotalCommander\SVN\SVNAdd.ahk
#Include *i WarstwaTotalCommander\SVN\SVNDelete.ahk
#Include *i WarstwaTotalCommander\SVN\SVNShowLog.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCheckLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNGetLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCleanUp.ahk
#Include *i WarstwaWord\MakraOgolne\HideSelectedText.ahk
#Include *i WarstwaWord\MakraOgolne\MSWordSetFont.ahk
#Include *i WarstwaWord\MakraOgolne\DeleteLineOfText.ahk
#Include *i WarstwaWord\MakraOgolne\ShowClipboard.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleApplyStylesPane.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleStylePane.ahk
#Include *i WarstwaWord\MakraOgolne\NavigationPaneVisibility.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleFormattingPane.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleSelectionAndVisibilityPane.ahk
#Include *i WarstwaWord\MakraOgolne\FormatObjectPane.ahk
#Include *i WarstwaWord\Recenzja\VersionAndAdjustationFinal.ahk
#Include *i WarstwaWord\Recenzja\VersionAndAdjustationOriginal.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\WatermarkDRAFT.ahk
#Include *i WarstwaWord\Obrazki\Group.ahk
#Include *i WarstwaWord\Obrazki\Ungroup.ahk
#Include *i WarstwaWord\Obrazki\RotateLeft90.ahk
#Include *i WarstwaWord\Obrazki\RotateRight90.ahk
#Include *i WarstwaWord\Obrazki\TextBoxWithStyleVerticallyAlignedTrue.ahk
#Include *i WarstwaWord\Obrazki\TextBoxWithStyleVerticallyAlignedFalse.ahk
#Include *i WarstwaWord\Obrazki\FlipVertically.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectLeft.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectUp.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectDown.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectRight.ahk
#Include *i WarstwaWord\Obrazki\FlipVertically.ahk
#Include *i WarstwaWord\Obrazki\FlipHorizontally.ahk
#Include *i WarstwaWord\Akapity\ParagraphPageBreakBefore.ahk
#Include *i WarstwaWord\Akapity\ParagraphFormatKeepWithNext.ahk
#Include *i WarstwaWord\Akapity\ParagraphLinesKeepTogether.ahk
#Include *i WarstwaWord\Akapity\DeleteInterline.ahk
#Include *i WarstwaWord\Akapity\ReapplyStyles.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\UstawMarginesy.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PierwszaStrona.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\StartWithOddOrEvenPage.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\OdstepPrzedSekcja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\Hiperlacza.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\ParzysteSekcje.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\UsunWielokrotneSpacje.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PrepareToPrint.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\TwardaSpacja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\OstatniaSekcja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\DodajNrSVN.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\WatermarkDRAFT.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\AutoTemplate.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\AutoTemplate.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PierwszaStrona.ahk
#Include *i WarstwaWord\MakraOgolne\Captions.ahk
#Include *i WarstwaWord\MakraOgolne\InsertHeadingNumber.ahk
#Include *i WarstwaWord\MakraOgolne\InsertHeadingText.ahk
#Include *i WarstwaWord\MakraOgolne\InsertEnumNumber.ahk
#Include *i WarstwaWord\MakraOgolne\InsertBookmarkText.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SetDefaultInterlines.ahk
||||||| .r848
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToStylesLayer.ahk
#Include *i Layer1\ToMacrosLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Style\Styl_Naglowek1.ahk
#Include *i Style\Styl_Naglowek2.ahk
#Include *i Style\Styl_Naglowek3.ahk
#Include *i Style\Styl_Naglowek4.ahk
#Include *i Style\Styl_Naglowek5.ahk
#Include *i Style\Styl_Naglowek6.ahk
#Include *i Style\Styl_Naglowek7.ahk
#Include *i Style\Styl_Naglowek8.ahk
#Include *i Style\Styl_NaglowekSpisuTresci.ahk
#Include *i Style\Styl_Normalny.ahk
#Include *i Style\Styl_NormalnyPomiedzy.ahk
#Include *i Style\Styl_Ukryty.ahk
#Include *i Style\Styl_Homoglify.ahk
#Include *i Style\Styl_Bezpieczenstwo.ahk
#Include *i Style\Styl_LiniaPrzerwy.ahk
#Include *i Style\Styl_Rysunek.ahk
#Include *i Style\Styl_PodpisPodRysunkiem.ahk
#Include *i Style\Styl_PolaTekstowe.ahk
#Include *i Style\Styl_Tabela.ahk
#Include *i Style\Styl_TabelaBezKrawedzi.ahk
#Include *i Style\Styl_NormalnyWTabeli.ahk
#Include *i Style\Styl_PodpisTabeli.ahk
#Include *i Style\Styl_Wypunktowanie.ahk
#Include *i Style\Styl_WypunktowanieReferencji.ahk
#Include *i Style\Styl_WypunktowanieWTabeli.ahk
#Include *i Style\Styl_NormalnyPunktowany.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Makra\SzablonPL.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Makra\SzablonEN.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek1.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek2.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek3.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek4.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek5.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek6.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek7.ahk
#Include *i Class_ImageButton.ahk
#Include *i WarstwaWord\Style\Styl_NaglowekSpisuTresci.ahk
#Include *i WarstwaWord\Style\Styl_Normalny.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyPomiedzy.ahk
#Include *i WarstwaWord\Style\Styl_Ukryty.ahk
#Include *i WarstwaWord\Style\Styl_Bezpieczenstwo.ahk
#Include *i WarstwaWord\Style\Styl_Homoglify.ahk
#Include *i WarstwaWord\Style\Styl_LiniaPrzerwy.ahk
#Include *i Class_ImageButton.ahk
#Include *i WarstwaWord\Style\Styl_PodpisPodRysunkiem.ahk
#Include *i WarstwaWord\Style\Styl_PolaTekstowe.ahk
#Include *i WarstwaWord\Style\Styl_Tabela.ahk
#Include *i WarstwaWord\Style\Styl_TabelaBezKrawedzi.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyWTabeli.ahk
#Include *i WarstwaWord\Style\Styl_PodpisTabeli.ahk
#Include *i WarstwaWord\Style\Styl_Wypunktowanie.ahk
#Include *i WarstwaWord\Style\Styl_WypunktowanieReferencji.ahk
#Include *i WarstwaWord\Style\Styl_WypunktowanieWTabeli.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyPunktowany.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek8.ahk
#Include *i WarstwaWord\Style\Styl_Rysunek.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek8.ahk
#Include *i WarstwaWord\Makra\SzablonPL.ahk
#Include *i WarstwaWord\Makra\SzablonEN.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\testtesttest.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToStylesLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToMacrosLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\Makra\SzablonPL.ahk
#Include *i WarstwaWord\Makra\SzablonEN.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_identyfikator.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_ListaZmian.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTresci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTabel.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisRysunkow.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisOznaczenGraficznych.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_tabela.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Kanwa.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaInformacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Zastrzezenie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_PierwszaStronaZwykla.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_NaglowekZwykly.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StopkaZwykla.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStronaObrazek.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStronaObrazek.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStrona.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\Makra\UstawMarginesy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i WarstwaWord\Makra\UstawMarginesy.ahk
#Include *i WarstwaWord\Makra\UsunWielokrotneSpacje.ahk
#Include *i WarstwaWord\Makra\PierwszaStrona.ahk
#Include *i WarstwaWord\Makra\UpdateSVNFields.ahk
#Include *i WarstwaWord\Makra\DodajNrSVN.ahk
#Include *i WarstwaWord\Makra\TwardaSpacja.ahk
#Include *i WarstwaWord\Makra\ZielenKolor.ahk
#Include *i WarstwaWord\Makra\UsunKolor.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToTCLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToTablesLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_DrugaStrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Producent.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_NewNextListPelna.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaInformacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaOstrzezenie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTresci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_InformacjeODokumencie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisSkrotow.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Referencje.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_ReferencjePodrozdzialy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SRAC.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OInstrukcji.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Ilustracje.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_newlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_newnumlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextnumlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_AXMCaly.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ReprezentacjaGraficznaAXM.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PodstawyKontroliNiezajetosci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ObslugaiEksploatacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PrzeznaczoneUzytkowanie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ZakresDostawy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Podziekowania.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_pustastrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_blankpage.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_KanwaZIkonami.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PrawaAutorskie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_RyzykoResztkowe.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_TekstOryginalny.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_UsuwanieOstatniejSekcji.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Utylizacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_UtylizacjaOpakowania.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToSVNLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisSkrotow.ahk
#Include *i WarstwaTotalCommander\SVN\SVNUpdate.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCommit.ahk
#Include *i WarstwaTotalCommander\SVN\SVNAdd.ahk
#Include *i WarstwaTotalCommander\SVN\SVNDelete.ahk
#Include *i WarstwaTotalCommander\SVN\SVNShowLog.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCheckLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNGetLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaWord\Tabele\InsertColumnToTheLeft.ahk
#Include *i WarstwaWord\Tabele\InsertColumnToTheRight.ahk
#Include *i WarstwaWord\Tabele\InsertTableRowAbove.ahk
#Include *i WarstwaWord\Tabele\InsertTableRowBelow.ahk
#Include *i WarstwaWord\Tabele\DeleteTableColumn.ahk
#Include *i WarstwaWord\Tabele\DeleteTableRow.ahk
#Include *i WarstwaWord\Tabele\SeparateTableCell1xRow2xColumn.ahk
#Include *i WarstwaWord\Tabele\SeparateTableCell2xRow1xColumn.ahk
#Include *i WarstwaWord\Tabele\MergeTableCells.ahk
#Include *i WarstwaWord\Tabele\MarkAllTableCells.ahk
#Include *i WarstwaWord\Tabele\AlignTableToPageBorder.ahk
#Include *i WarstwaWord\Tabele\DopasowanieTabeli.ahk
#Include *i WarstwaWord\Tabele\RepeatTableHeader.ahk
#Include *i WarstwaWord\Tabele\TableRowsAllowBreakAcrossPages.ahk
#Include *i WarstwaWord\Tabele\AlignTableCellConntentToLeft.ahk
#Include *i WarstwaWord\Tabele\AlignTableCellConntentToMiddle.ahk
#Include *i WarstwaWord\Tabele\TableCellColorVoestalpine.ahk
#Include *i WarstwaWord\MakraOgolne\ShowHiddenText.ahk
#Include *i WarstwaWord\MakraOgolne\StrikeThroughText.ahk
#Include *i WarstwaWord\MakraOgolne\Header.ahk
#Include *i WarstwaWord\MakraOgolne\Footer.ahk
#Include *i WarstwaWord\MakraOgolne\FullPath.ahk
#Include *i WarstwaWord\MakraOgolne\ZielenKolor.ahk
#Include *i WarstwaWord\MakraOgolne\UsunKolor.ahk
#Include *i WarstwaWord\MakraOgolne\GranicePol.ahk
#Include *i WarstwaWord\MakraOgolne\PrintToPdf.ahk
#Include *i WarstwaWord\MakraOgolne\ChangeZoom.ahk
#Include *i WarstwaWord\MakraOgolne\DisplayGridLines.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleRuler.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToParagraphLayer.ahk
#Include *i Layer1\ToSettingsLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToImagesLayer.ahk
#Include *i Layer1\ToReviewLayer.ahk
#Include *i Layer1\ToListsLayer.ahk
#Include *i WarstwaWord\Obrazki\HorizontalLine.ahk
#Include *i WarstwaWord\Obrazki\PolaTekstowe.ahk
#Include *i WarstwaWord\Akapity\Lista1Poz.ahk
#Include *i WarstwaWord\Akapity\Lista1PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista2Poz.ahk
#Include *i WarstwaWord\Akapity\Lista2PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista3Poz.ahk
#Include *i WarstwaWord\Akapity\Lista3PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista4Poz.ahk
#Include *i WarstwaWord\Akapity\Lista4PozKont.ahk
#Include *i WarstwaWord\Akapity\ChangeLanguage.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SzablonPL.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SzablonEN.ahk
#Include *i WarstwaWord\Recenzja\EditComment.ahk
#Include *i WarstwaWord\Recenzja\GoToNextComment.ahk
#Include *i WarstwaWord\Recenzja\GoToPreviousComment.ahk
#Include *i WarstwaWord\Recenzja\NextChangeOrComment.ahk
#Include *i WarstwaWord\Recenzja\PreviousChangeOrComment.ahk
#Include *i WarstwaWord\Recenzja\DeleteCurrentComment.ahk
#Include *i WarstwaWord\Recenzja\AcceptChange.ahk
#Include *i WarstwaWord\Recenzja\RejectChange.ahk
#Include *i WarstwaWord\Wypunktowania\BB_newlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_newnumlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nextnumlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_NewNextListPelna.ahk
#Include *i WarstwaWord\Wypunktowania\BB_NewNextListPelna.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToTCLayer.ahk
#Include *i WarstwaTotalCommander\SVN\SVNUpdate.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCommit.ahk
#Include *i WarstwaTotalCommander\SVN\SVNAdd.ahk
#Include *i WarstwaTotalCommander\SVN\SVNDelete.ahk
#Include *i WarstwaTotalCommander\SVN\SVNShowLog.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCheckLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNGetLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCleanUp.ahk
#Include *i WarstwaWord\MakraOgolne\HideSelectedText.ahk
#Include *i WarstwaWord\MakraOgolne\MSWordSetFont.ahk
#Include *i WarstwaWord\MakraOgolne\DeleteLineOfText.ahk
#Include *i WarstwaWord\MakraOgolne\ShowClipboard.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleApplyStylesPane.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleStylePane.ahk
#Include *i WarstwaWord\MakraOgolne\NavigationPaneVisibility.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleFormattingPane.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleSelectionAndVisibilityPane.ahk
#Include *i WarstwaWord\MakraOgolne\FormatObjectPane.ahk
#Include *i WarstwaWord\Recenzja\VersionAndAdjustationFinal.ahk
#Include *i WarstwaWord\Recenzja\VersionAndAdjustationOriginal.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\WatermarkDRAFT.ahk
#Include *i WarstwaWord\Obrazki\Group.ahk
#Include *i WarstwaWord\Obrazki\Ungroup.ahk
#Include *i WarstwaWord\Obrazki\RotateLeft90.ahk
#Include *i WarstwaWord\Obrazki\RotateRight90.ahk
#Include *i WarstwaWord\Obrazki\TextBoxWithStyleVerticallyAlignedTrue.ahk
#Include *i WarstwaWord\Obrazki\TextBoxWithStyleVerticallyAlignedFalse.ahk
#Include *i WarstwaWord\Obrazki\FlipVertically.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectLeft.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectUp.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectDown.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectRight.ahk
#Include *i WarstwaWord\Obrazki\FlipVertically.ahk
#Include *i WarstwaWord\Obrazki\FlipHorizontally.ahk
#Include *i WarstwaWord\Akapity\ParagraphPageBreakBefore.ahk
#Include *i WarstwaWord\Akapity\ParagraphFormatKeepWithNext.ahk
#Include *i WarstwaWord\Akapity\ParagraphLinesKeepTogether.ahk
#Include *i WarstwaWord\Akapity\DeleteInterline.ahk
#Include *i WarstwaWord\Akapity\ReapplyStyles.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\UstawMarginesy.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PierwszaStrona.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\StartWithOddOrEvenPage.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\OdstepPrzedSekcja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\Hiperlacza.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\ParzysteSekcje.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\UsunWielokrotneSpacje.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PrepareToPrint.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\TwardaSpacja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\OstatniaSekcja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\DodajNrSVN.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\WatermarkDRAFT.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\AutoTemplate.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\AutoTemplate.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PierwszaStrona.ahk
#Include *i WarstwaWord\MakraOgolne\Captions.ahk
#Include *i WarstwaWord\MakraOgolne\InsertHeadingNumber.ahk
#Include *i WarstwaWord\MakraOgolne\InsertHeadingText.ahk
#Include *i WarstwaWord\MakraOgolne\InsertEnumNumber.ahk
#Include *i WarstwaWord\MakraOgolne\InsertBookmarkText.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SetDefaultInterlines.ahk
=======
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToStylesLayer.ahk
#Include *i Layer1\ToMacrosLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Style\Styl_Naglowek1.ahk
#Include *i Style\Styl_Naglowek2.ahk
#Include *i Style\Styl_Naglowek3.ahk
#Include *i Style\Styl_Naglowek4.ahk
#Include *i Style\Styl_Naglowek5.ahk
#Include *i Style\Styl_Naglowek6.ahk
#Include *i Style\Styl_Naglowek7.ahk
#Include *i Style\Styl_Naglowek8.ahk
#Include *i Style\Styl_NaglowekSpisuTresci.ahk
#Include *i Style\Styl_Normalny.ahk
#Include *i Style\Styl_NormalnyPomiedzy.ahk
#Include *i Style\Styl_Ukryty.ahk
#Include *i Style\Styl_Homoglify.ahk
#Include *i Style\Styl_Bezpieczenstwo.ahk
#Include *i Style\Styl_LiniaPrzerwy.ahk
#Include *i Style\Styl_Rysunek.ahk
#Include *i Style\Styl_PodpisPodRysunkiem.ahk
#Include *i Style\Styl_PolaTekstowe.ahk
#Include *i Style\Styl_Tabela.ahk
#Include *i Style\Styl_TabelaBezKrawedzi.ahk
#Include *i Style\Styl_NormalnyWTabeli.ahk
#Include *i Style\Styl_PodpisTabeli.ahk
#Include *i Style\Styl_Wypunktowanie.ahk
#Include *i Style\Styl_WypunktowanieReferencji.ahk
#Include *i Style\Styl_WypunktowanieWTabeli.ahk
#Include *i Style\Styl_NormalnyPunktowany.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Makra\SzablonPL.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Makra\SzablonEN.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek1.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek2.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek3.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek4.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek5.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek6.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek7.ahk
#Include *i Class_ImageButton.ahk
#Include *i WarstwaWord\Style\Styl_NaglowekSpisuTresci.ahk
#Include *i WarstwaWord\Style\Styl_Normalny.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyPomiedzy.ahk
#Include *i WarstwaWord\Style\Styl_Ukryty.ahk
#Include *i WarstwaWord\Style\Styl_Bezpieczenstwo.ahk
#Include *i WarstwaWord\Style\Styl_Homoglify.ahk
#Include *i WarstwaWord\Style\Styl_LiniaPrzerwy.ahk
#Include *i Class_ImageButton.ahk
#Include *i WarstwaWord\Style\Styl_PodpisPodRysunkiem.ahk
#Include *i WarstwaWord\Style\Styl_PolaTekstowe.ahk
#Include *i WarstwaWord\Style\Styl_Tabela.ahk
#Include *i WarstwaWord\Style\Styl_TabelaBezKrawedzi.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyWTabeli.ahk
#Include *i WarstwaWord\Style\Styl_PodpisTabeli.ahk
#Include *i WarstwaWord\Style\Styl_Wypunktowanie.ahk
#Include *i WarstwaWord\Style\Styl_WypunktowanieReferencji.ahk
#Include *i WarstwaWord\Style\Styl_WypunktowanieWTabeli.ahk
#Include *i WarstwaWord\Style\Styl_NormalnyPunktowany.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek8.ahk
#Include *i WarstwaWord\Style\Styl_Rysunek.ahk
#Include *i WarstwaWord\Style\Styl_Naglowek8.ahk
#Include *i WarstwaWord\Makra\SzablonPL.ahk
#Include *i WarstwaWord\Makra\SzablonEN.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\testtesttest.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToStylesLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i Layer1\ToMacrosLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\Makra\SzablonPL.ahk
#Include *i WarstwaWord\Makra\SzablonEN.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i Layer1\ToWordLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_identyfikator.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_ListaZmian.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTresci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTabel.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisRysunkow.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisOznaczenGraficznych.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_tabela.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Kanwa.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaInformacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Zastrzezenie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_PierwszaStronaZwykla.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_NaglowekZwykly.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StopkaZwykla.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStronaObrazek.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStronaObrazek.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStrona.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\Makra\UstawMarginesy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i WarstwaWord\Makra\UstawMarginesy.ahk
#Include *i WarstwaWord\Makra\UsunWielokrotneSpacje.ahk
#Include *i WarstwaWord\Makra\PierwszaStrona.ahk
#Include *i WarstwaWord\Makra\UpdateSVNFields.ahk
#Include *i WarstwaWord\Makra\DodajNrSVN.ahk
#Include *i WarstwaWord\Makra\TwardaSpacja.ahk
#Include *i WarstwaWord\Makra\ZielenKolor.ahk
#Include *i WarstwaWord\Makra\UsunKolor.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToTCLayer.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToTablesLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_DrugaStrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Producent.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_NewNextListPelna.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaInformacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaOstrzezenie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTresci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_InformacjeODokumencie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisSkrotow.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_Referencje.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_ReferencjePodrozdzialy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SRAC.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_OInstrukcji.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Ilustracje.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_newlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnnewlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nnnnextlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_newnumlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_nextnumlist.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_AXMCaly.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ReprezentacjaGraficznaAXM.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PodstawyKontroliNiezajetosci.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ObslugaiEksploatacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PrzeznaczoneUzytkowanie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_ZakresDostawy.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Podziekowania.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_pustastrona.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_blankpage.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_KanwaZIkonami.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_PrawaAutorskie.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_RyzykoResztkowe.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_TekstOryginalny.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_UsuwanieOstatniejSekcji.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_Utylizacja.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne2\BB_UtylizacjaOpakowania.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToSVNLayer.ahk
#Include *i WarstwaWord\BlokiKonstrukcyjne1\BB_SpisSkrotow.ahk
#Include *i WarstwaTotalCommander\SVN\SVNUpdate.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCommit.ahk
#Include *i WarstwaTotalCommander\SVN\SVNAdd.ahk
#Include *i WarstwaTotalCommander\SVN\SVNDelete.ahk
#Include *i WarstwaTotalCommander\SVN\SVNShowLog.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCheckLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNGetLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaWord\Tabele\InsertColumnToTheLeft.ahk
#Include *i WarstwaWord\Tabele\InsertColumnToTheRight.ahk
#Include *i WarstwaWord\Tabele\InsertTableRowAbove.ahk
#Include *i WarstwaWord\Tabele\InsertTableRowBelow.ahk
#Include *i WarstwaWord\Tabele\DeleteTableColumn.ahk
#Include *i WarstwaWord\Tabele\DeleteTableRow.ahk
#Include *i WarstwaWord\Tabele\SeparateTableCell1xRow2xColumn.ahk
#Include *i WarstwaWord\Tabele\SeparateTableCell2xRow1xColumn.ahk
#Include *i WarstwaWord\Tabele\MergeTableCells.ahk
#Include *i WarstwaWord\Tabele\MarkAllTableCells.ahk
#Include *i WarstwaWord\Tabele\AlignTableToPageBorder.ahk
#Include *i WarstwaWord\Tabele\DopasowanieTabeli.ahk
#Include *i WarstwaWord\Tabele\RepeatTableHeader.ahk
#Include *i WarstwaWord\Tabele\TableRowsAllowBreakAcrossPages.ahk
#Include *i WarstwaWord\Tabele\AlignTableCellConntentToLeft.ahk
#Include *i WarstwaWord\Tabele\AlignTableCellConntentToMiddle.ahk
#Include *i WarstwaWord\Tabele\TableCellColorVoestalpine.ahk
#Include *i WarstwaWord\MakraOgolne\ShowHiddenText.ahk
#Include *i WarstwaWord\MakraOgolne\StrikeThroughText.ahk
#Include *i WarstwaWord\MakraOgolne\Header.ahk
#Include *i WarstwaWord\MakraOgolne\Footer.ahk
#Include *i WarstwaWord\MakraOgolne\FullPath.ahk
#Include *i WarstwaWord\MakraOgolne\ZielenKolor.ahk
#Include *i WarstwaWord\MakraOgolne\UsunKolor.ahk
#Include *i WarstwaWord\MakraOgolne\GranicePol.ahk
#Include *i WarstwaWord\MakraOgolne\PrintToPdf.ahk
#Include *i WarstwaWord\MakraOgolne\ChangeZoom.ahk
#Include *i WarstwaWord\MakraOgolne\DisplayGridLines.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleRuler.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToParagraphLayer.ahk
#Include *i Layer1\ToSettingsLayer.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToImagesLayer.ahk
#Include *i Layer1\ToReviewLayer.ahk
#Include *i Layer1\ToListsLayer.ahk
#Include *i WarstwaWord\Obrazki\HorizontalLine.ahk
#Include *i WarstwaWord\Obrazki\PolaTekstowe.ahk
#Include *i WarstwaWord\Akapity\Lista1Poz.ahk
#Include *i WarstwaWord\Akapity\Lista1PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista2Poz.ahk
#Include *i WarstwaWord\Akapity\Lista2PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista3Poz.ahk
#Include *i WarstwaWord\Akapity\Lista3PozKont.ahk
#Include *i WarstwaWord\Akapity\Lista4Poz.ahk
#Include *i WarstwaWord\Akapity\Lista4PozKont.ahk
#Include *i WarstwaWord\Akapity\ChangeLanguage.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SzablonPL.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SzablonEN.ahk
#Include *i WarstwaWord\Recenzja\EditComment.ahk
#Include *i WarstwaWord\Recenzja\GoToNextComment.ahk
#Include *i WarstwaWord\Recenzja\GoToPreviousComment.ahk
#Include *i WarstwaWord\Recenzja\NextChangeOrComment.ahk
#Include *i WarstwaWord\Recenzja\PreviousChangeOrComment.ahk
#Include *i WarstwaWord\Recenzja\DeleteCurrentComment.ahk
#Include *i WarstwaWord\Recenzja\AcceptChange.ahk
#Include *i WarstwaWord\Recenzja\RejectChange.ahk
#Include *i WarstwaWord\Wypunktowania\BB_newlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnnewlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nnnnextlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_newnumlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_nextnumlist.ahk
#Include *i WarstwaWord\Wypunktowania\BB_NewNextListPelna.ahk
#Include *i WarstwaWord\Wypunktowania\BB_NewNextListPelna.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i Layer1\ToTCLayer.ahk
#Include *i WarstwaTotalCommander\SVN\SVNUpdate.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCommit.ahk
#Include *i WarstwaTotalCommander\SVN\SVNAdd.ahk
#Include *i WarstwaTotalCommander\SVN\SVNDelete.ahk
#Include *i WarstwaTotalCommander\SVN\SVNShowLog.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCheckLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNGetLock.ahk
#Include *i WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i WarstwaTotalCommander\SVN\SVNCleanUp.ahk
#Include *i WarstwaWord\MakraOgolne\HideSelectedText.ahk
#Include *i WarstwaWord\MakraOgolne\MSWordSetFont.ahk
#Include *i WarstwaWord\MakraOgolne\DeleteLineOfText.ahk
#Include *i WarstwaWord\MakraOgolne\ShowClipboard.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleApplyStylesPane.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleStylePane.ahk
#Include *i WarstwaWord\MakraOgolne\NavigationPaneVisibility.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleFormattingPane.ahk
#Include *i WarstwaWord\MakraOgolne\ToggleSelectionAndVisibilityPane.ahk
#Include *i WarstwaWord\MakraOgolne\FormatObjectPane.ahk
#Include *i WarstwaWord\Recenzja\VersionAndAdjustationFinal.ahk
#Include *i WarstwaWord\Recenzja\VersionAndAdjustationOriginal.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\WatermarkDRAFT.ahk
#Include *i WarstwaWord\Obrazki\Group.ahk
#Include *i WarstwaWord\Obrazki\Ungroup.ahk
#Include *i WarstwaWord\Obrazki\RotateLeft90.ahk
#Include *i WarstwaWord\Obrazki\RotateRight90.ahk
#Include *i WarstwaWord\Obrazki\TextBoxWithStyleVerticallyAlignedTrue.ahk
#Include *i WarstwaWord\Obrazki\TextBoxWithStyleVerticallyAlignedFalse.ahk
#Include *i WarstwaWord\Obrazki\FlipVertically.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectLeft.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectUp.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectDown.ahk
#Include *i WarstwaWord\Obrazki\MoveVectorObjectRight.ahk
#Include *i WarstwaWord\Obrazki\FlipVertically.ahk
#Include *i WarstwaWord\Obrazki\FlipHorizontally.ahk
#Include *i WarstwaWord\Akapity\ParagraphPageBreakBefore.ahk
#Include *i WarstwaWord\Akapity\ParagraphFormatKeepWithNext.ahk
#Include *i WarstwaWord\Akapity\ParagraphLinesKeepTogether.ahk
#Include *i WarstwaWord\Akapity\DeleteInterline.ahk
#Include *i WarstwaWord\Akapity\ReapplyStyles.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\UstawMarginesy.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PierwszaStrona.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\StartWithOddOrEvenPage.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\OdstepPrzedSekcja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\Hiperlacza.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\ParzysteSekcje.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\UsunWielokrotneSpacje.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PrepareToPrint.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\TwardaSpacja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\OstatniaSekcja.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\DodajNrSVN.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\WatermarkDRAFT.ahk
#Include *i Layer1\ToBuildingBlocksLayer2.ahk
#Include *i Layer1\ToFirstLayer.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\AutoTemplate.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\AutoTemplate.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\PierwszaStrona.ahk
#Include *i WarstwaWord\MakraOgolne\Captions.ahk
#Include *i WarstwaWord\MakraOgolne\InsertHeadingNumber.ahk
#Include *i WarstwaWord\MakraOgolne\InsertHeadingText.ahk
#Include *i WarstwaWord\MakraOgolne\InsertEnumNumber.ahk
#Include *i WarstwaWord\MakraOgolne\InsertBookmarkText.ahk
#Include *i Layer1\ToBuildingBlocksLayer.ahk
#Include *i WarstwaWord\UstawieniaDokumentu\SetDefaultInterlines.ahk
#Include *i WarstwaWord\MakraOgolne\SetHeadersAndFooters.ahk
>>>>>>> .r856
