#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToStylesLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToMacrosLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Naglowek1.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Naglowek2.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Naglowek3.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Naglowek4.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Naglowek5.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Naglowek6.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Naglowek7.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Naglowek8.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_NaglowekSpisuTresci.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Normalny.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_NormalnyPomiedzy.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Ukryty.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Homoglify.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Bezpieczenstwo.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_LiniaPrzerwy.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Rysunek.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_PodpisPodRysunkiem.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_PolaTekstowe.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Tabela.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_TabelaBezKrawedzi.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_NormalnyWTabeli.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_PodpisTabeli.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_Wypunktowanie.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_WypunktowanieReferencji.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_WypunktowanieWTabeli.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Style\Styl_NormalnyPunktowany.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Makra\SzablonPL.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Makra\SzablonEN.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToBuildingBlocksLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek1.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek2.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek3.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek4.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek5.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek6.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek7.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Class_ImageButton.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_NaglowekSpisuTresci.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Normalny.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_NormalnyPomiedzy.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Ukryty.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Bezpieczenstwo.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Homoglify.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_LiniaPrzerwy.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Class_ImageButton.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_PodpisPodRysunkiem.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_PolaTekstowe.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Tabela.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_TabelaBezKrawedzi.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_NormalnyWTabeli.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_PodpisTabeli.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Wypunktowanie.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_WypunktowanieReferencji.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_WypunktowanieWTabeli.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_NormalnyPunktowany.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek8.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Rysunek.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Style\Styl_Naglowek8.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\SzablonPL.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\SzablonEN.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToBuildingBlocksLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\testtesttest.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToStylesLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToMacrosLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToBuildingBlocksLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\SzablonPL.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\SzablonEN.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToWordLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_identyfikator.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_ListaZmian.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTresci.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTabel.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_SpisRysunkow.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_SpisOznaczenGraficznych.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_tabela.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_Kanwa.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaInformacja.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_Zastrzezenie.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_PierwszaStronaZwykla.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_NaglowekZwykly.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_StopkaZwykla.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStrona.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStronaObrazek.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStronaObrazek.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_OstatniaStrona.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\UstawMarginesy.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_StronaOzdobna.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\UstawMarginesy.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\UsunWielokrotneSpacje.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\PierwszaStrona.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\UpdateSVNFields.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\DodajNrSVN.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\TwardaSpacja.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\ZielenKolor.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Makra\UsunKolor.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToTCLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToBuildingBlocksLayer2.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToTablesLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_DrugaStrona.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_Producent.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_NewNextListPelna.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaInformacja.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_TabelaOstrzezenie.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_SpisTresci.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_InformacjeODokumencie.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_SpisSkrotow.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_Referencje.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_ReferencjePodrozdzialy.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_SRAC.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_OInstrukcji.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToBuildingBlocksLayer2.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_Ilustracje.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_newlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nextlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nextlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nnewlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nnextlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nnnewlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nnnextlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nnnnewlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nnnnextlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_newnumlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_nextnumlist.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_AXMCaly.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_ReprezentacjaGraficznaAXM.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_PodstawyKontroliNiezajetosci.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_ObslugaiEksploatacja.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_PrzeznaczoneUzytkowanie.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_ZakresDostawy.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_Podziekowania.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_pustastrona.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_blankpage.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_KanwaZIkonami.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_PrawaAutorskie.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_RyzykoResztkowe.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_TekstOryginalny.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_UsuwanieOstatniejSekcji.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_Utylizacja.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne2\BB_UtylizacjaOpakowania.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToBuildingBlocksLayer2.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToSVNLayer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\BlokiKonstrukcyjne1\BB_SpisSkrotow.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNUpdate.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNCommit.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNAdd.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNDelete.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNShowLog.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNCheckLock.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNGetLock.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaTotalCommander\SVN\SVNRename.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\InsertColumnToTheLeft.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\InsertColumnToTheRight.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\InsertTableRowAbove.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\InsertTableRowBelow.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\DeleteTableColumn.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\DeleteTableRow.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\SeparateTableCell1xRow2xColumn.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\SeparateTableCell2xRow1xColumn.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\MergeTableCells.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\MarkAllTableCells.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\AlignTableToPageBorder.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\DopasowanieTabeli.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\RepeatTableHeader.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\TableRowsAllowBreakAcrossPages.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\AlignTableCellConntentToLeft.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\AlignTableCellConntentToMiddle.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\Tabele\TableCellColorVoestalpine.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\ShowHiddenText.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\StrikeThroughText.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\Header.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\Footer.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\FullPath.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\ZielenKolor.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\UsunKolor.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\GranicePol.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\PrintToPdf.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\ChangeZoom.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\DisplayGridLines.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\WarstwaWord\MakraOgolne\ToggleRuler.ahk
#Include *i C:\Repozytoria\CompanyTemplates\AutoHotKeyScripts\Otagle\Layer1\ToFirstLayer.ahk
