Hotstring(":B0*:pwm", func("NormalWay").bind("{Backspace 3}PWM"), "On")
Hotstring(":*:PWM.", func("NormalWay").bind("Pulse-Width Modulation"), "On")
Hotstring(":B0*:usa", func("NormalWay").bind("{Backspace 3}USA"), "On")
Hotstring(":*:USA.", func("ViaClipboard").bind("United States of America"), "On")
Hotstring(":*:hsz31", func("NormalWay").bind("HSZ31"), "On")
Hotstring(":B0*:cot", func("NormalWay").bind("{Backspace 3}CoT"), "On")
Hotstring(":*:CoT.", func("NormalWay").bind("Clearance of Track"), "On")
Hotstring(":B0*:led", func("NormalWay").bind("{BackSpace 3}LED"), "On")
Hotstring(":*:LED.", func("NormalWay").bind("Light Emitting Diode"), "On")
Hotstring(":*:orcad", func("NormalWay").bind("OrCAD"), "On")
Hotstring(":B0*:qna", func("NormalWay").bind("{Backspace 3}Q&A"), "On")
Hotstring(":*:qna.", func("ViaClipboard").bind("Questions and Answers"), "On")
Hotstring(":B0*:api", func("NormalWay").bind("{BackSpace 3}API"), "On")
Hotstring(":*:API.", func("ViaClipboard").bind("Application Programming Interface"), "On")
Hotstring("::eg", func("NormalWay").bind("e.g."), "On")
