Hotstring(":B0*:pwm", func("NormalWay").bind("{Backspace 3}PWM"), "On")
Hotstring(":*:PWM.", func("NormalWay").bind("Pulse-Width Modulation"), "On")
Hotstring(":B0*:usa", func("NormalWay").bind("{Backspace 3}USA"), "On")
Hotstring(":*:USA.", func("ViaClipboard").bind("United States of America"), "On")
Hotstring(":*:hsz31", func("NormalWay").bind("HSZ31"), "On")
Hotstring(":B0*:cot", func("NormalWay").bind("{Backspace 3}CoT"), "On")
Hotstring(":*:CoT.", func("NormalWay").bind("Clearance of Track"), "On")
Hotstring(":B0*:led", func("NormalWay").bind("{BackSpace 3}LED"), "On")
Hotstring(":*:LED.", func("NormalWay").bind("Light Emitting Diode"), "On")
Hotstring(":*:orcad", func("NormalWay").bind("OrCAD"), "On")
Hotstring(":B0*:qna", func("NormalWay").bind("{Backspace 3}Q&A"), "On")
Hotstring(":*:qna.", func("ViaClipboard").bind("Questions and Answers"), "On")
Hotstring(":B0*:api", func("NormalWay").bind("{BackSpace 3}API"), "On")
Hotstring(":*:API.", func("ViaClipboard").bind("Application Programming Interface"), "On")
Hotstring("::eg", func("NormalWay").bind("e.g."), "On")
Hotstring("::ie", func("NormalWay").bind("i.e."), "On")
Hotstring(":B0*:sql", func("NormalWay").bind("{BackSpace 3}SQL"), "On")
Hotstring(":*:sql.", func("ViaClipboard").bind("Structured Query Language"), "On")
Hotstring(":B0:ux", func("NormalWay").bind("{Backspace 3}UX"), "On")
Hotstring(":*:ux.", func("ViaClipboard").bind("User Experience"), "On")
Hotstring(":*:cu.", func("ViaClipboard").bind("Competence Unit"), "On")
Hotstring(":*:dlds.", func("NormalWay").bind("Drive, Locking, Detection & Signaling"), "On")
Hotstring(":*:dmt rs.", func("ViaClipboard").bind("Diagnostic and Monitoring Technologies for Rolling Stock"), "Off")
Hotstring(":*:dmti.", func("ViaClipboard").bind("Diagnostic and Monitoring Technologies for Infrastructure"), "On")
Hotstring(":B0*:axc", func("NormalWay").bind("{BackSpace 3}AxC"), "On")
Hotstring(":*:axc.", func("ViaClipboard").bind("Axle Counter"), "On")
Hotstring(":B0*:dlds", func("NormalWay").bind("{BackSpace 4}DLD/S"), "On")
Hotstring(":*:dmtrs.", func("ViaClipboard").bind("Diagnostic and Monitoring Technologies for Rolling Stock"), "On")
Hotstring(":B0*:dmtrs", func("NormalWay").bind("{BackSpace 5}DMT RS"), "On")
Hotstring(":B0*:dmti", func("NormalWay").bind("{BackSpace 4}DMT Infra"), "On")
Hotstring(":*:cfo.", func("NormalWay").bind("Chief Financial Officer"), "On")
Hotstring(":B0*:cfo", func("NormalWay").bind("{BackSpace 3}CFO"), "On")
Hotstring(":B0*:cso", func("NormalWay").bind("{BackSpace 3}CSO"), "On")
Hotstring(":*:cso.", func("NormalWay").bind("Chief Sales Officer"), "On")
Hotstring(":B0*:covid", func("NormalWay").bind("{BackSpace 5}COVID-19"), "On")
Hotstring(":*:covid.", func("ViaClipboard").bind("{BackSpace 3}severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)"), "On")
Hotstring(":*:vvv.", func("ViaClipboard").bind("Vereinigte Österreichische Eisen und Stahlwerke & Österreichisch-Alpine Montangengesellschaft"), "On")
Hotstring(":B0*:ui", func("NormalWay").bind("{BackSpace 2}UI"), "On")
Hotstring(":*:ui.", func("ViaClipboard").bind("User Interface"), "On")
Hotstring(":*:can.", func("ViaClipboard").bind("Controller Area Network"), "On")
Hotstring(":B0*:can", func("NormalWay").bind("{BackSpace 3}CAN"), "On")
Hotstring(":*:shcl.", func("ViaClipboard").bind("TW-2090-171R-SoftwareandHardwareCompatibilityLog.xlsx"), "On")
Hotstring(":*:tbc.", func("ViaClipboard").bind("to be continued"), "On")
Hotstring(":*:pkb.", 			func("ViaClipboard").bind("Produkt Narodowy Brutto"), "On")
Hotstring(":B0*:pkb", 			func("NormalWay").bind("{Backspace 3}PKB"), "On")
Hotstring(":*:siwz.", 			func("ViaClipboard").bind("Specyfikacja Istotnych Warunków Zamówienia"), "On")
Hotstring(":B0*:siwz", 			func("NormalWay").bind("{BackSpace 4}SIWZ"), "On")
