Hotstring(":*:polska",			func("ViaClipboard").bind("Polska"))
Hotstring(":*:poland",			func("ViaClipboard").bind("Poland"))
Hotstring(":*:polish",			func("ViaClipboard").bind("Polish"))
Hotstring(":*:english",			func("ViaClipboard").bind("English"))
Hotstring(":*:german",			func("ViaClipboard").bind("German"))
Hotstring(":*:germany",			func("ViaClipboard").bind("Germany"))
Hotstring(":*:a la",			func("ViaClipboard").bind("à la"))
Hotstring(":*:a propos",		func("ViaClipboard").bind("à propos"))
Hotstring(":*:apropos",			func("ViaClipboard").bind("à propos"))
Hotstring(":*:fyi.",			func("ViaClipboard").bind("For your information"))
Hotstring(":*:asap.",			func("ViaClipboard").bind("as soon as possible"))
Hotstring(":*:afaik.",			func("ViaClipboard").bind("as far as I know"))
Hotstring(":*:btw.",			func("ViaClipboard").bind("by the way"))
Hotstring(":b0*?:email",		func("NormalWay").bind("{Backspace 5}e-mail"))
Hotstring(":*:sharepoint",		func("ViaClipboard").bind("Sharepoint"))
Hotstring(":*:sp.",				func("ViaClipboard").bind("Sharepoint"))