Hotstring(":*:svn",				func("ViaClipboard").bind("SVN"))
Hotstring(":*:sap",				func("ViaClipboard").bind("SAP"))
Hotstring(":*:easm.",			func("ViaClipboard").bind("EASM"))
Hotstring(":*:qnx",				func("ViaClipboard").bind("QNX"))
Hotstring(":*:rs232",			func("ViaClipboard").bind("RS232"))
Hotstring(":*:rs485",			func("ViaClipboard").bind("RS485"))
Hotstring(":*:uic60",			func("ViaClipboard").bind("UIC60"))
Hotstring(":*:s49",				func("ViaClipboard").bind("S49"))
Hotstring(":*:iscala",			func("ViaClipboard").bind("iSCALA"))
Hotstring(":*:ditaexchange",	func("ViaClipboard").bind("DitaExchange"))
Hotstring(":*:pma",				func("ViaClipboard").bind("PMAN"))
Hotstring(":*:dokt",			func("ViaClipboard").bind("DokT (Dokumentacja Techniczna)"))
Hotstring(":*:dokr",			func("ViaClipboard").bind("DokR (Dokumentacja Robocza)"))
Hotstring(":*:easm",			func("ViaClipboard").bind("EASM"))