Hotstring(":*:rene",			func("ViaClipboard").bind("René"))
Hotstring(":*:guenther",		func("ViaClipboard").bind("Günther"))
Hotstring(":*:pek",				func("ViaClipboard").bind("Pék"))
Hotstring(":*:stuhn",			func("ViaClipboard").bind("Stühn"))
Hotstring(":*:joerg",			func("ViaClipboard").bind("Jörg"))
Hotstring(":*:jorg",			func("ViaClipboard").bind("Jörg"))
Hotstring(":*:soren",			func("ViaClipboard").bind("Søren"))
Hotstring(":*:js.",				func("ViaClipboard").bind("Jarosław Stec"))
Hotstring(":*:masz.",			func("ViaClipboard").bind("Maciej Szczepański"))
Hotstring(":*:mib.",			func("ViaClipboard").bind("Michał Bigus"))
Hotstring(":*:pw.",				func("ViaClipboard").bind("Przemysław Wołoszyk"))
Hotstring(":*:ag.",				func("ViaClipboard").bind("Ariadna Grzona"))
Hotstring(":*:gl.",				func("ViaClipboard").bind("Günther Lehner"))
Hotstring(":*:rb.",				func("ViaClipboard").bind("René Berger"))
Hotstring(":*:jm.",				func("ViaClipboard").bind("Jan Mironkiewicz"))
Hotstring(":*:nb.",				func("ViaClipboard").bind("Natalia Budzińska"))
Hotstring(":*:mo.",				func("ViaClipboard").bind("Mariusz Ossowski"))
Hotstring(":*:pp.",				func("ViaClipboard").bind("Piotr Pék"))
Hotstring(":*:fb.",				func("ViaClipboard").bind("Filip Bisztyga"))
Hotstring(":*:sm.",				func("ViaClipboard").bind("Sebastian Meyer"))
Hotstring(":*:pl.",				func("ViaClipboard").bind("Przemysław Latarski"))
Hotstring(":*:pk.",				func("ViaClipboard").bind("Paweł Kopacz"))
Hotstring(":*:jd.",				func("ViaClipboard").bind("Joanna Damrat"))
Hotstring(":*:rg.",				func("ViaClipboard").bind("Rafał Golicki"))
Hotstring(":*:kw.",				func("ViaClipboard").bind("Kamil Wilkanowski"))
Hotstring(":*:mg.",				func("ViaClipboard").bind("Michalina Gołąbek"))
Hotstring(":*:zk.",				func("ViaClipboard").bind("Zbigniew Kosiak"))
Hotstring(":*:km.",				func("ViaClipboard").bind("Krzysztof Michalak"))
Hotstring(":*:ks.",				func("ViaClipboard").bind("Krystian Stasiński"))
Hotstring(":*:tw.",				func("ViaClipboard").bind("Trąbki Wielkie"))
Hotstring(":*:aw.",				func("ViaClipboard").bind("Agata Wilary"))
Hotstring(":*:mn.",				func("ViaClipboard").bind("Marta Nibus"))
Hotstring(":*:je.",				func("ViaClipboard").bind("Jörg Engers"))
Hotstring(":*:jam.",			func("ViaClipboard").bind("Jakub Masiak"))