Hotstring(":*:tuv.",		func("ViaClipboard").bind("German: Technischer Überwachungsverein, English: Technical Inspection Association ` "))
Hotstring("::tuv",			func("ViaClipboard").bind("TÜV"))
Hotstring("::sud",			func("ViaClipboard").bind("SÜD"))
Hotstring(":*:gmbh.",		func("ViaClipboard").bind("German: Gesellschaft mit beschränkter Haftung, English: company with limited liability ` "))
Hotstring("::gmbh",			func("ViaClipboard").bind("GmbH ` "))
Hotstring(":*:obb.",		func("ViaClipboard").bind("German: Österreichische Bundesbahnen, English: Austrian Federal Railways ` "))
Hotstring("::obb",			func("ViaClipboard").bind("ÖBB ` "))
Hotstring(":*:sbb.",		func("ViaClipboard").bind("German: Schweizerische Bundesbahnen, English: Swiss Federal Railways"))
Hotstring("::sbb",			func("ViaClipboard").bind("SBB"))