Hotstring(":*:dd",			func("ViaClipboard").bind("Dzień dobry, " . Chr(0x000B) . Chr(0x000B) ))
Hotstring(":*:pms",			func("ViaClipboard").bind("Pozdrawia ms"))
Hotstring(":*:m.",			func("ViaClipboard").bind("Maciej"))
Hotstring(":*:s.",			func("ViaClipboard").bind("Słojewski"))
Hotstring(":*:telms",			func("ViaClipboard").bind("+48 601 403 775"))
Hotstring(":*:ms.",			func("ViaClipboard").bind("Maciej Słojewski"))
Hotstring(":b0*:m@2",		func("NormalWay").bind("{BackSpace 17}@mslonik.pl"))
Hotstring(":b0*:m@",		func("NormalWay").bind("{BackSpace 2}maciej.slojewski@voestalpine.com"))
Hotstring(":*:zws",			func("ViaClipboard").bind("Z wyrazami szacunku`, Maciej Słojewski"))
Hotstring(":c*:kr`t",		func("ViaClipboard").bind("Kind regards`, Maciej Słojewski"))
Hotstring(":*:dw.",			func("ViaClipboard").bind("Do wiadomości.`r`n`r`nPozdrawia ms"))
Hotstring(":*:v.",			func("ViaClipboard").bind("V523580"))