Hotstring(":*:dtr.",			func("ViaClipboard").bind("Dokumentacja Techniczno-Ruchowa"))
Hotstring("::dtr",				func("ViaClipboard").bind("DTR"))
Hotstring(":*:wtwio.",			func("ViaClipboard").bind("Warunki Techniczne Wytwarzania i Odbioru"))
Hotstring("::wtwio",			func("ViaClipboard").bind("WTWiO"))
Hotstring(":*:pkp.",			func("ViaClipboard").bind("Polskie Koleje Państwowe"))
Hotstring("::pkp",				func("ViaClipboard").bind("PKP"))
Hotstring(":*:plk.",			func("ViaClipboard").bind("Polskie Linie Kolejowe"))
Hotstring("::plk",				func("ViaClipboard").bind("PLK"))
Hotstring(":*:ik.",				func("ViaClipboard").bind("Instytut Kolejnictwa"))
Hotstring("::ik",				func("ViaClipboard").bind("IK"))
Hotstring(":*:pesel.",			func("ViaClipboard").bind("Powszechny Elektroniczny System Ewidencji Ludności"))
Hotstring("::pesel",			func("ViaClipboard").bind("PESEL"))
Hotstring(":*:utk.",			func("ViaClipboard").bind("Urząd Transportu Kolejowego"))
Hotstring("::utk",				func("ViaClipboard").bind("UTK"))
Hotstring(":*:bait.",			func("ViaClipboard").bind("Biuro Automatyki i Telekomunikacji"))
Hotstring("::bait",				func("ViaClipboard").bind("BAiT"))
Hotstring(":*:bhp.",			func("ViaClipboard").bind("Bezpieczeństwo i Higiena Pracy"))
Hotstring("::bhp",				func("ViaClipboard").bind("BHP"))
Hotstring(":*:srk.",			func("ViaClipboard").bind( "(urządzenia) sterowania ruchem kolejowym"))
Hotstring(":*:nip.",			func("ViaClipboard").bind("Numer Identyfikacji Podatkowej"))
Hotstring("::nip",				func("ViaClipboard").bind("NIP"))
Hotstring(":*:ersat.",			func("ViaClipboard").bind("Elektroniczny Rejestr Stanów Awaryjnych Taboru"))
Hotstring("::ersat",			func("ViaClipboard").bind("ERSAT"))