Hotstring(":*:axmpl.",				func("ViaClipboard").bind("moduł uniwersalny"))
Hotstring(":*:axmen.",				func("ViaClipboard").bind("universal module"))
Hotstring(":b0*:axm",				func("NormalWay").bind("{BackSpace 3}AXM"))
Hotstring(":*:axmrpl.",			func("ViaClipboard").bind("moduł uniwersalny rozszerzony o wyjścia przekaźnikowe"))
Hotstring(":*:axmren.",			func("ViaClipboard").bind("universal module extended with relay outputs"))
Hotstring(":*:axmr",				func("NormalWay").bind("AXM^=R^="))
Hotstring(":*:axmiopl.",			func("ViaClipboard").bind("moduł uniwersalny rozszerzony o wejścia i wyjścia binarne"))
Hotstring(":*:axmioen.",			func("ViaClipboard").bind("universal module extended with binary inputs and outputs"))
Hotstring(":*:axmio",				func("NormalWay").bind("AXM^=IO^="))	
Hotstring(":*:axma",				func("NormalWay").bind("AXM{Space}/{Space}AXM^=R^={Space}/{Space}AXM^=IO^="))
Hotstring(":b0*x:axmp.",			func("NormalWay").bind("{BackSpace 5}AXM,{Space}AXM^=R^=,{Space}AXM^=IO^="))
Hotstring(":*:nout",				func("ViaClipboard").bind("~OUT"))
Hotstring(":*:cok.",				func("ViaClipboard").bind("czujnik koła"))
Hotstring(":*b0:cok",				func("NormalWay").bind("{Backspace 3}COK"))
Hotstring(":*:wsu.",				func("ViaClipboard").bind("wheel sensor unit"))
Hotstring(":*b0:wsu",				func("NormalWay").bind("{Backspace 3}WSU"))
Hotstring(":*:ihd1",				func("NormalWay").bind("I^=HD1^="))
Hotstring(":*:ihd2",				func("NormalWay").bind("I^=HD2^="))
Hotstring(":*:hd1en.",				func("ViaClipboard").bind("HD1 (the 1st head of wheel sensor)"))
Hotstring(":*:hd2en.",				func("ViaClipboard").bind("HD2 (the 2nd head of wheel sensor)"))
Hotstring(":*:hd1pl.",				func("ViaClipboard").bind("HD1 (pierwsza głowica czujnika koła)"))
Hotstring(":*:hd2pl.",				func("ViaClipboard").bind("HD2 (druga głowica czujnika koła)"))
Hotstring(":*:uniacpl.",			func("ViaClipboard").bind("(uniwersalny) system liczenia osi"))
Hotstring(":*:uniacen.",			func("ViaClipboard").bind("(universal) axle counting system"))
Hotstring(":b0*:uniac",			func("NormalWay").bind("{BackSpace 5}UniAC"))
Hotstring(":*:uniac2pl.",			func("ViaClipboard").bind("(uniwersalny) system liczenia osi drugiej generacji"))
Hotstring(":*:uniac2en.",			func("ViaClipboard").bind("(universal) axle counting system of 2nd generation"))
Hotstring(":b0*:uniac2",			func("NormalWay").bind("{BackSpace 6}UniAC[2]"))
Hotstring(":*:uniac1pl.",			func("ViaClipboard").bind("(uniwersalny) system liczenia osi pierwszej generacji"))
Hotstring(":*:uniac1en.",			func("ViaClipboard").bind("(universal) axle counting system of 1st generation"))
Hotstring(":b0*:uniac1",			func("NormalWay").bind("{BackSpace 6}UniAC[1]"))
Hotstring(":*:uniacxpl.",			func("ViaClipboard").bind("rodzina uniwersalnych systemów liczenia osi"))
Hotstring(":*:uniacxen.",			func("ViaClipboard").bind("family of universal axle counting system"))
Hotstring(":b0*:uniacx",			func("NormalWay").bind("{BackSpace 6}UniAC[x]"))
Hotstring(":*:unias1ppl.",			func("NormalWay").bind("{BackSpace 2}(uniwersalny) czujnik koła typu UniAS[1{+}]"))
Hotstring(":*:unias1pen.",			func("ViaClipboard").bind("(universal) UniAS[1{+}] type wheel sensor"))
Hotstring(":b0*:unias1p",			func("NormalWay").bind("{BackSpace 9}UniAS[1{+}]"))
Hotstring(":*:unias2ipl.",			func("ViaClipboard").bind("(uniwersalny) czujnik koła typu UniAS[2i]"))
Hotstring(":*:unias2ien.",			func("ViaClipboard").bind("(universal) UniAS[2i] type wheel sensor"))
Hotstring(":b0*:unias2i",			func("NormalWay").bind("{BackSpace 9}UniAS[2i]"))
Hotstring(":*:unias1pl.",			func("ViaClipboard").bind("(uniwersalny) czujnik koła typu UniAS[1]"))
Hotstring(":*:unias1en.",			func("ViaClipboard").bind("(universal) UniAS[1] type wheel sensor"))
Hotstring(":b0*:unias1",			func("NormalWay").bind("{BackSpace 6}UniAS[1]"))
Hotstring(":*:unias2pl.",			func("ViaClipboard").bind("(uniwersalny) czujnik koła typu UniAS[2]"))
Hotstring(":*:unias2en.",			func("ViaClipboard").bind("(universal) UniAS[2] type wheel sensor"))
Hotstring(":b0*:unias2",			func("NormalWay").bind("{BackSpace 6}UniAS[2]"))
Hotstring(":*:uniasxpl.",			func("ViaClipboard").bind("rodzina (uniwersalnych) czujników osi"))
Hotstring(":*:uniasxen.",			func("ViaClipboard").bind("(universal) wheel sensor family"))
Hotstring(":b0*:uniasx",			func("NormalWay").bind("{BackSpace 6}UniAS[x]"))		
Hotstring(":*:uniaspl.",			func("ViaClipboard").bind("(uniwersalny) czujnik koła"))
Hotstring(":*:uniasen.",			func("ViaClipboard").bind("(universal) wheel sensor"))
Hotstring(":b0*:unias",			func("NormalWay").bind("{BackSpace 5}UniAS"))
Hotstring(":*:unircpl.",			func("ViaClipboard").bind("(uniwersalny) uchwyt czujnika koła"))
Hotstring(":*:unircen.",			func("ViaClipboard").bind("(universal) wheel sensor rail clamp"))
Hotstring(":*b0:unirc",			func("NormalWay").bind("{Backspace 5}UniRC"))
Hotstring(":*:azcpl.",				func("ViaClipboard").bind("moduł ochrony przeciwprzepięciowej dedykowany dla rodziny czujników osi UniAS[x]"))
Hotstring(":*:azcen.",				func("ViaClipboard").bind("surge protection module dedicated for UniAS[x] wheel sensor family"))
Hotstring(":*b0:azc",				func("NormalWay").bind("{Backspace 3}AZC"))
Hotstring(":*:magpl.",				func("ViaClipboard").bind("magistrala"))
Hotstring(":*:magen.",				func("ViaClipboard").bind("backplane"))
Hotstring(":b0*:mag",				func("NormalWay").bind("{Backspace 3}MAG"))
Hotstring(":b0*:magsacpl.",			func("NormalWay").bind("{BackSpace 37}zintegrowany moduł diagnostyczny, komunikacyjny i zasilający"))
Hotstring(":b0*:magsacen.",			func("NormalWay").bind("{BackSpace 37}integrated diagnostic, communication and voltage supply module"))
Hotstring(":*:header.",			func("ViaClipboard").bind("integrated diagnostic, communication and voltage supply module"))
Hotstring(":*b0:magsac",			func("NormalWay").bind("{Backspace 6}MAG_SAC (MAGSUP + MAG_ADM + MAG_COM)"))
Hotstring(":*b0:magsak",			func("NormalWay").bind("{Backspace 6}MAG_SAC (MAGSUP + MAG_ADM + MAG_COM)"))
Hotstring(":*:magsuppl.",			func("ViaClipboard").bind("moduł zasilający"))
Hotstring(":*:magsupen.",			func("ViaClipboard").bind("voltage supply module"))
Hotstring(":*b0:magsup",			func("NormalWay").bind("{Backspace 3}MAG_SUP"))
Hotstring(":*:magadmen.",			func("ViaClipboard").bind("basic diagnostic module"))
Hotstring(":*:magadmpl.",			func("ViaClipboard").bind("moduł podstawowej diagnostyki"))
Hotstring(":*b0:magadm",			func("NormalWay").bind("{Backspace 3}MAG_ADM"))
Hotstring(":*:admpl.",				func("ViaClipboard").bind("moduł rozszerzonej diagnostyki"))
Hotstring(":*:admen.",				func("ViaClipboard").bind("extended diagnostics module"))
Hotstring(":*b0:adm",				func("NormalWay").bind("{Backspace 3}ADM"))
Hotstring(":*:mrupl.",				func("ViaClipboard").bind("moduł rozszerzonej diagnostyki"))
Hotstring(":*:mruen.",				func("ViaClipboard").bind("module rack unit"))
Hotstring(":*b0:mru",				func("NormalWay").bind("{Backspace 3}MRU"))
Hotstring(":*:asmpl.",				func("ViaClipboard").bind("moduł oceniający"))
Hotstring(":*:asmen.",				func("ViaClipboard").bind("evaluation module"))
Hotstring(":*b0:asm",				func("NormalWay").bind("{Backspace 3}ASM"))
Hotstring(":*:acmpl.",				func("ViaClipboard").bind("moduł liczący"))
Hotstring(":*:acmen.",				func("ViaClipboard").bind("counting module"))
Hotstring(":*b0:acm",				func("NormalWay").bind("{Backspace 3}ACM"))
Hotstring(":*:aimpl.",				func("ViaClipboard").bind("moduł wejść wyjść"))
Hotstring(":*:aimen.",				func("ViaClipboard").bind("inputs and outputs module"))
Hotstring(":*b0:aim",				func("NormalWay").bind("{Backspace 3}AIM"))
Hotstring(":*:abmpl.",				func("ViaClipboard").bind("kaseta"))
Hotstring(":*:abmen.",				func("ViaClipboard").bind("module rack"))
Hotstring(":*b0:abm",				func("NormalWay").bind("{Backspace 3}ABM"))
Hotstring(":*:anszuapl.",			func("ViaClipboard").bind("system zarządzania usługami"))
Hotstring(":*b0:anszua",			func("NormalWay").bind("{Backspace 6}AnSzuA"))
Hotstring(":*:uniblpl.",			func("ViaClipboard").bind("system (uniwersalnej) blokady liniowej"))
Hotstring(":*:uniblen.",			func("ViaClipboard").bind("UniBL"))
Hotstring(":*b0:unibl",			func("NormalWay").bind("{Backspace 5}UniBL"))
Hotstring(":*:dsat.",				func("ViaClipboard").bind("detekcja Stanówaryjnych Taboru"))
Hotstring(":*b0:dsat",				func("NormalWay").bind("{Backspace 4}dSAT"))
Hotstring(":*:asdek.",				func("ViaClipboard").bind("automatyczny system detekcji i eksploatacji kół pojazdów kolejowych"))
Hotstring(":*b0:asdek",			func("NormalWay").bind("{Backspace 5}ASDEK"))
Hotstring(":*:s2d.",				func("ViaClipboard").bind("szlakowy system diagnostyki"))
Hotstring(":*b0:s2d",				func("NormalWay").bind("{Backspace 3}SSD"))
Hotstring(":*:gotcha",				func("ViaClipboard").bind("GOTCHA"))
Hotstring(":*:phoenix",			func("ViaClipboard").bind("PHOENIX"))
Hotstring(":*b0:pm",				func("NormalWay").bind("{Backspace 2}PM"))
Hotstring(":*:dp.",				func("ViaClipboard").bind("Dział Produkcji i Zaopatrzenia"))
Hotstring(":*b0:dp",				func("NormalWay").bind("{Backspace 2}DPiZ"))
Hotstring(":*:dpiz.",				func("ViaClipboard").bind("Dział Produkcji i Zaopatrzenia"))
Hotstring(":*b0:dpiz",				func("NormalWay").bind("{Backspace 4}DPiZ"))
Hotstring(":*:du.",				func("ViaClipboard").bind("Dział Usług i Realizacji"))
Hotstring(":*b0:du",				func("NormalWay").bind("{Backspace 2}DUiR"))
Hotstring(":*:duir.",				func("ViaClipboard").bind("Dział Usług i Realizacji"))
Hotstring(":*b0:duir",				func("NormalWay").bind("{Backspace 6}DUiR"))
Hotstring(":*:dr.",				func("ViaClipboard").bind("Dział Rozwoju"))
Hotstring(":*b0:dr",				func("NormalWay").bind("{Backspace 2}DR"))
Hotstring(":*:wim.",				func("ViaClipboard").bind("Weighing in Motion"))
Hotstring(":*b0:wim",				func("NormalWay").bind("{Backspace 3}WIM"))
Hotstring(":*:wdd.",				func("ViaClipboard").bind("Wheel Defect Detection"))
Hotstring(":*b0:wdd",				func("NormalWay").bind("{Backspace 3}WDD"))
Hotstring(":*:hbd.",				func("ViaClipboard").bind("Hot-Box Detector"))
Hotstring(":*b0:hbd",				func("NormalWay").bind("{Backspace 3}HBD"))
Hotstring(":*:hwd.",				func("ViaClipboard").bind("Hot-Wheel Detector"))
Hotstring(":*b0:hwd",				func("NormalWay").bind("{Backspace 3}HWD"))
Hotstring(":*:mb.",				func("ViaClipboard").bind("Multi Beam"))
Hotstring(":*b0:mb",				func("NormalWay").bind("{Backspace 2}MB"))
Hotstring(":*:mds.",				func("ViaClipboard").bind("modułlar Diagnostic System"))
Hotstring(":*b0:mds",				func("NormalWay").bind("{Backspace 3}MDS"))
Hotstring(":b0o:vo",				func("ViaClipboard").bind("estalpine"))
Hotstring(":*b0:voe",				func("ViaClipboard").bind("stalpine Signaling Sopot"))
Hotstring("::voes",				func("NormalWay").bind("{BackSpace} Sp. z o.o."))
Hotstring(":z*b0:voesi",			func("NormalWay").bind("{Backspace 17}Siershahn"))
Hotstring(":*:si.",				func("ViaClipboard").bind("Siershahn"))
Hotstring(":*:so.",				func("ViaClipboard").bind("Sopot"))
Hotstring(":*:sai.",				func("ViaClipboard").bind("Sainerholz"))
Hotstring(":*:nipv.",				func("ViaClipboard").bind("584-025-39-29"))
Hotstring(":*:adres.",				func("ViaClipboard").bind("Jana z Kolna 26c, 81-859 Sopot, Polska"))
Hotstring(":*:addres2.",			func("ViaClipboard").bind("Jana z Kolna 26c, 81-859 Sopot, Poland"))
Hotstring(":*:hpir.",				func("ViaClipboard").bind("Hardware Prototype Implementation Report"))
Hotstring(":*b0:hpir",				func("NormalWay").bind("{Backspace 4}HPIR"))
Hotstring(":*:rnd.",				func("ViaClipboard").bind("Research & Development"))
Hotstring(":*b0:rnd",				func("NormalWay").bind("{Backspace 3}R&D"))
Hotstring(":*b0:cps",				func("NormalWay").bind("{Backspace 3}Cooperation Platform Sopot (https://solidsystemteamwork.voestalpine.root.local/internalprojects/vaSupp/CPS/SitePages/Home.aspx)"))
Hotstring(":*:muk",				func("ViaClipboard").bind("MDS Upgrade Kit (https://solidsystemteamwork.voestalpine.root.local/Processes/custprojects/780MDSUpgradeKit/SitePages/Home.aspx)"))
Hotstring(":*b0:sps",				func("NormalWay").bind("{Backspace 3}Documentation Sharepoint Sopot"" (https://team.voestalpine.net/site/4077/default.aspx)"))
Hotstring(":*:bbt.",				func("ViaClipboard").bind("Bearing and Brake Temperature"))
Hotstring(":*b0:bbt",				func("NormalWay").bind("{Backspace 3}BBT"))
Hotstring(":B0*:unirc", func("NormalWay").bind("{BackSpace 5}UniRC"))